# nvchecker definitions for local/custom packages in packages/core/.

[access-launcher]
source = "github"
github = "boo15mario/access-launcher"
use_max_tag = false
use_latest_release = false

[universal-startup-manager]
source = "github"
github = "boo15mario/universal-startup-manager"
use_max_tag = false
use_latest_release = false
