#!/usr/bin/env bash
set -euo pipefail

die() {
  echo "Error: $*" >&2
  exit 1
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

EXTRA_LIST_FILE="${EXTRA_LIST_FILE:-${REPO_ROOT}/packages/extra.list}"
PACKAGES_DIR="${PACKAGES_DIR:-${REPO_ROOT}/packages}"
LOCAL_NVCHECKER_TOML="${LOCAL_NVCHECKER_TOML:-${REPO_ROOT}/metadata/nvchecker/local.toml}"
AUR_NVCHECKER_TOML="${AUR_NVCHECKER_TOML:-${REPO_ROOT}/metadata/nvchecker/aur.toml}"
UPDATES_JSON="${UPDATES_JSON:-${REPO_ROOT}/metadata/upstream-updates.json}"
UPDATES_MD="${UPDATES_MD:-${REPO_ROOT}/metadata/upstream-updates.md}"
AUR_BATCH_SIZE="${AUR_BATCH_SIZE:-50}"

read_list() {
  local list_file="$1"
  [[ -f "${list_file}" ]] || return 0
  while IFS= read -r line; do
    line="${line%%#*}"
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -n "${line}" ]] && printf '%s\n' "${line}"
  done <"${list_file}"
}

require_cmd jq
require_cmd nvchecker
require_cmd curl

mkdir -p -- "$(dirname -- "${AUR_NVCHECKER_TOML}")" "$(dirname -- "${UPDATES_JSON}")"
mkdir -p -- "${REPO_ROOT}/work"

srcinfo_from_dir() {
  local pkg_dir="$1"

  if [[ -f "${pkg_dir}/.SRCINFO" ]]; then
    cat "${pkg_dir}/.SRCINFO"
    return 0
  fi

  (cd "${pkg_dir}" && makepkg --printsrcinfo)
}

version_from_srcinfo() {
  local srcinfo_text="$1"
  local epoch pkgver pkgrel

  epoch="$(awk -F' = ' '{gsub(/^[[:space:]]+|[[:space:]]+$/, "", $1); gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2)} $1=="epoch"{print $2; exit}' <<<"${srcinfo_text}" || true)"
  pkgver="$(awk -F' = ' '{gsub(/^[[:space:]]+|[[:space:]]+$/, "", $1); gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2)} $1=="pkgver"{print $2; exit}' <<<"${srcinfo_text}")"
  pkgrel="$(awk -F' = ' '{gsub(/^[[:space:]]+|[[:space:]]+$/, "", $1); gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2)} $1=="pkgrel"{print $2; exit}' <<<"${srcinfo_text}")"

  [[ -n "${pkgver}" && -n "${pkgrel}" ]] || die "failed to parse pkgver/pkgrel from .SRCINFO"

  if [[ -n "${epoch}" && "${epoch}" != "0" ]]; then
    printf '%s:%s-%s\n' "${epoch}" "${pkgver}" "${pkgrel}"
  else
    printf '%s-%s\n' "${pkgver}" "${pkgrel}"
  fi
}

add_srcinfo_versions() {
  local -n versions_ref="$1"
  local srcinfo_text="$2"
  local version pkgname
  local -a pkgnames=()

  version="$(version_from_srcinfo "${srcinfo_text}")"
  mapfile -t pkgnames < <(awk -F' = ' '{gsub(/^[[:space:]]+|[[:space:]]+$/, "", $1); gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2)} $1=="pkgname"{print $2}' <<<"${srcinfo_text}" | sort -u)
  for pkgname in "${pkgnames[@]}"; do
    versions_ref="$(jq -c --arg pkg "${pkgname}" --arg ver "${version}" '. + {($pkg): $ver}' <<<"${versions_ref}")"
  done
}

resolve_pages_base_url() {
  local remote_url parsed owner repo_name

  if [[ -n "${PAGES_BASE_URL:-}" ]]; then
    printf '%s\n' "${PAGES_BASE_URL%/}"
    return 0
  fi

  if [[ -n "${GITHUB_REPOSITORY_OWNER:-}" && -n "${GITHUB_REPOSITORY:-}" ]]; then
    repo_name="${GITHUB_REPOSITORY#*/}"
    printf 'https://%s.github.io/%s\n' "${GITHUB_REPOSITORY_OWNER}" "${repo_name}"
    return 0
  fi

  remote_url="$(git -C "${REPO_ROOT}" remote get-url origin 2>/dev/null || true)"
  [[ -n "${remote_url}" ]] || return 1
  parsed="$(sed -nE 's#^.*[:/]([^/:]+)/([^/]+)(\.git)?$#\1 \2#p' <<<"${remote_url}")"
  [[ -n "${parsed}" ]] || return 1
  owner="${parsed%% *}"
  repo_name="${parsed#* }"
  repo_name="${repo_name%.git}"
  printf 'https://%s.github.io/%s\n' "${owner}" "${repo_name}"
}

fetch_published_manifest() {
  local base_url
  base_url="$(resolve_pages_base_url)" || return 1
  curl -fsSL "${base_url}/manifest.json" | jq -S .
}

generate_aur_nvchecker_toml() {
  local pkg
  mapfile -t AUR_PACKAGES < <(read_list "${EXTRA_LIST_FILE}")

  {
    echo '# Generated by `scripts/check-upstream-updates.sh`.'
    echo '# Do not edit by hand; update `packages/extra.list` instead.'
    for pkg in "${AUR_PACKAGES[@]}"; do
      printf '\n[%s]\n' "${pkg}"
      printf 'source = "aur"\n'
      printf 'aur = "%s"\n' "${pkg}"
    done
  } >"${AUR_NVCHECKER_TOML}"
}

config_package_names() {
  local file="$1"
  [[ -f "${file}" ]] || return 0
  awk '
    /^\[__config__\]$/ { next }
    /^\[[^]]+\]$/ {
      name=$0
      sub(/^\[/, "", name)
      sub(/\]$/, "", name)
      print name
    }
  ' "${file}"
}

current_versions_json='{}'

if [[ -d "${PACKAGES_DIR}/core" ]]; then
  while IFS= read -r -d '' pkgbuild; do
    pkg_dir="$(cd -- "$(dirname -- "${pkgbuild}")" && pwd)"
    srcinfo="$(srcinfo_from_dir "${pkg_dir}")"
    add_srcinfo_versions current_versions_json "${srcinfo}"
  done < <(find "${PACKAGES_DIR}/core" -mindepth 2 -maxdepth 2 -type f -name PKGBUILD -print0)
fi

while IFS= read -r pkg; do
  [[ -n "${pkg}" ]] || continue
  pkg_dir="${PACKAGES_DIR}/extra/${pkg}"
  if [[ -d "${pkg_dir}" && -f "${pkg_dir}/PKGBUILD" ]]; then
    srcinfo="$(srcinfo_from_dir "${pkg_dir}")"
    add_srcinfo_versions current_versions_json "${srcinfo}"
  fi
done < <(read_list "${EXTRA_LIST_FILE}")

published_manifest='{}'
if published_manifest="$(fetch_published_manifest 2>/dev/null)"; then
  :
fi

generate_aur_nvchecker_toml

work_dir="$(mktemp -d "${REPO_ROOT%/}/work/upstream.XXXXXXXX")"
cleanup() {
  rm -rf -- "${work_dir}"
}
trap cleanup EXIT

oldver_file="${work_dir}/oldver.toml"
newver_file="${work_dir}/newver.toml"
combined_toml="${work_dir}/nvchecker.toml"

{
  echo '[__config__]'
  printf 'oldver = "%s"\n' "${oldver_file}"
  printf 'newver = "%s"\n' "${newver_file}"
  cat "${AUR_NVCHECKER_TOML}"
  [[ -f "${LOCAL_NVCHECKER_TOML}" ]] && cat "${LOCAL_NVCHECKER_TOML}"
} >"${combined_toml}"

: >"${oldver_file}"
while IFS= read -r pkg; do
  [[ -n "${pkg}" ]] || continue
  current_ver="$(jq -r --arg pkg "${pkg}" '.[$pkg] // empty' <<<"${current_versions_json}")"
  if [[ -z "${current_ver}" ]]; then
  current_ver="$(jq -r --arg pkg "${pkg}" '
      .repos["access-os-core"].packages[$pkg]
      // .repos["access-os-extra"].packages[$pkg]
      // empty
    ' <<<"${published_manifest}")"
  fi
  [[ -n "${current_ver}" ]] || continue
  printf '%s = "%s"\n' "${pkg}" "${current_ver}" >>"${oldver_file}"
done < <(
  {
    config_package_names "${AUR_NVCHECKER_TOML}"
    config_package_names "${LOCAL_NVCHECKER_TOML}"
  } | sort -u
)

nvchecker_output="${work_dir}/nvchecker.log"
set +e
nvchecker -c "${combined_toml}" --logger both >"${nvchecker_output}" 2>&1
nvchecker_rc="$?"
set -e

new_versions_json='{}'
if [[ -f "${newver_file}" ]]; then
  while IFS= read -r line; do
    [[ "${line}" == *=* ]] || continue
    pkg="${line%%=*}"
    pkg="${pkg%"${pkg##*[![:space:]]}"}"
    value="${line#*=}"
    value="${value#"${value%%[![:space:]]*}"}"
    value="${value%\"}"
    value="${value#\"}"
    new_versions_json="$(jq -c --arg pkg "${pkg}" --arg ver "${value}" '. + {($pkg): $ver}' <<<"${new_versions_json}")"
  done <"${newver_file}"
fi

aur_names="$(config_package_names "${AUR_NVCHECKER_TOML}" | jq -R . | jq -s .)"
local_names="$(config_package_names "${LOCAL_NVCHECKER_TOML}" | jq -R . | jq -s .)"

report_json="$(
  jq -n \
    --argjson current "${current_versions_json}" \
    --argjson latest "${new_versions_json}" \
    --argjson aur "${aur_names:-[]}" \
    --argjson local "${local_names:-[]}" \
    '
    ($aur + $local | unique | sort) as $pkgs
    | [
        $pkgs[]
        | . as $pkg
        | {
            package: $pkg,
            source: (if ($aur | index($pkg)) != null then "aur" else "local" end),
            current_version: ($current[$pkg] // ""),
            latest_version: ($latest[$pkg] // ""),
            status: (
              if ($latest[$pkg] // "") == "" then "check-failed"
              elif ($current[$pkg] // "") == "" then "current-unknown"
              elif ($current[$pkg] == $latest[$pkg]) then "up-to-date"
              else "update-available"
              end
            )
          }
      ]
    '
)"

printf '%s\n' "${report_json}" | jq -S . >"${UPDATES_JSON}"

{
  echo "# Upstream Updates"
  echo
  echo "| Package | Source | Current | Latest | Status |"
  echo "|---------|--------|---------|--------|--------|"
  jq -r '.[] | "| `\(.package)` | `\(.source)` | `\(.current_version // "")` | `\(.latest_version // "")` | `\(.status)` |"' "${UPDATES_JSON}"
  if [[ "${nvchecker_rc}" -ne 0 ]]; then
    echo
    echo "## NVChecker Output"
    echo
    echo '```text'
    cat "${nvchecker_output}"
    echo '```'
  fi
} >"${UPDATES_MD}"

if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
  cat "${UPDATES_MD}" >>"${GITHUB_STEP_SUMMARY}"
fi

if [[ "${nvchecker_rc}" -ne 0 ]]; then
  echo "Warning: nvchecker returned a non-zero exit code; check-failed entries were recorded." >&2
fi
